# Generated by Django 3.0.8 on 2021-01-15 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backs', '0003_lecturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=6, primary_key='True', serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('shortname', models.CharField(max_length=4)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backs.Department')),
            ],
        ),
    ]
