# Generated by Django 3.0.8 on 2021-01-15 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backs', '0004_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='shortname',
            new_name='short_name',
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
