# Generated by Django 3.0.8 on 2021-01-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backs', '0005_auto_20210115_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.CharField(help_text='department_name(EE),Faculty(E)XXX', max_length=6, primary_key='True', serialize=False),
        ),
    ]
