# Generated by Django 3.0.8 on 2021-01-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backs', '0006_auto_20210115_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassId',
            fields=[
                ('Short_name', models.CharField(choices=[('100lvl', '100lvl'), ('200lvl', '200lvl'), ('300lvl', '300lvl'), ('400lvl', '400lvl'), ('500lvl', '500lvl')], max_length=6, primary_key=True, serialize=False)),
                ('ClassLevel', models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year'), ('Fifth Year', 'Fifth Year'), ('Final Year', 'Final Year')], max_length=12)),
            ],
        ),
    ]
