# Generated by Django 3.0.8 on 2021-01-18 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backs', '0007_classid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassId',
        ),
    ]
