# Generated by Django 3.0.8 on 2021-01-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backs', '0010_auto_20210118_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studclass',
            name='Id',
            field=models.CharField(choices=[('100lvl', '100lvl'), ('200lvl', '200lvl'), ('300lvl', '300lvl'), ('400lvl', '400lvl'), ('400lvl', '400lvl'), ('500lvl', '500lvl')], max_length=6, primary_key='True', serialize=False),
        ),
        migrations.AlterField(
            model_name='studclass',
            name='Year',
            field=models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year'), ('Fifth Year', 'Fifth Year'), ('Final Year', 'Final Year')], max_length=12),
        ),
    ]
