# Generated by Django 3.0.8 on 2021-01-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backs', '0012_auto_20210118_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studclass',
            name='Year',
        ),
        migrations.AlterField(
            model_name='studclass',
            name='Id',
            field=models.CharField(choices=[('100lvl', '100lvl'), ('200lvl', '200lvl'), ('300lvl', '300lvl'), ('400lvl', '400lvl'), ('500lvl', '500lvl')], max_length=6, primary_key='True', serialize=False),
        ),
    ]
