# Generated by Django 3.0.8 on 2021-01-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backs', '0013_auto_20210118_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studlevel',
            fields=[
                ('Id', models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year'), ('Fifth Year', 'Fifth Year'), ('Final Year', 'Final Year')], max_length=12, primary_key='True', serialize=False)),
            ],
        ),
    ]
