# Generated by Django 3.0.8 on 2021-01-18 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backs', '0014_studlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backs.Studlevel')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backs.Course')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backs.Department')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backs.Lecturer')),
            ],
            options={
                'unique_together': {('course', 'class_level', 'dept', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='Time_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_table', models.CharField(choices=[('8:00 - 10:00', '8:00 - 10:00'), ('8:00 - 9:00', '8:00 - 9:00'), ('9:00 - 10:00', '9:00 - 9:00'), ('9:00 - 11:00', '9:00 - 11:00'), ('10:00 - 11:00', '10:00 - 11:00'), ('10:00 - 12:00', '10:00 - 12:00'), ('11:00 - 12:00', '11:00 - 12:00'), ('12:00 - 13:00', '12:00 - 13:00'), ('13:00 - 14:00', '13:00 - 14:00'), ('13:00 - 15:00', '13:00 - 15:00'), ('14:00 - 15:00', '14:00 - 15:00'), ('14:00 - 16:00', '14:00 - 16:00'), ('15:00 - 16:00', '15:00 - 16:00'), ('15:00 - 17:00', '16:00 - 17:00'), ('16:00 - 17:00', '16:00 - 17:00')], max_length=30)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20)),
                ('names', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backs.TimeTable')),
            ],
        ),
    ]
