# Generated by Django 3.0.8 on 2021-01-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backs', '0018_auto_20210118_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studclass',
            old_name='Id',
            new_name='id',
        ),
    ]
